```
val connectionStatus = for {  
  host1 <- config.get("host")  
  port1 <- config.get("port")  
  x <- Connection(host1, port1)  
} {  
    println(s"I got the connection ${x.connect}")  
}
```


## `Try[T]`
- multiple/nested try's make the code hard to follow
- Try is a wrapper for a computation that might fail or not
- the Try abstract class is extended by two different case classes
	- `Failure[+T]` wrap failed computations
		- holds the throwable that would have been thrown 
	- `Success[+T]` wrap succeeded computations
		- holds the value returned by the computation
```
import scala.util.Success

val aSuccess = Success("Tindu")
val afailure = Failure(new RuntimeException("Super Failure"))

println(aSuccess)
println(afailure)
// Success(Tindu)
// Failure(java.lang.RuntimeException: Super Failure)
```
- most of the time we do not have to create success or failures ourselves
	- we can use the Try's apply method
```
import scala.util.Try
def unsafeMethod: String = throw new RuntimeException("No String")
println(Try(unsafeMethod)) // inferred type is Try[String]
```
- syntactic sugar:
```
val apotentialfailure: Try[Int] = Try {  
  val tend = 0  
  val ten = 10  
  10 / 0  
}  
println(apotentialfailure) // Failure(java.lang.ArithmeticException: / by zero)
```
- utilities available on the Try object
	- isSuccess
		- method that returns a boolean indicating whether the operation was successful
		- `println(apotentialfailure.isSuccess)`
	- isFailure
		- `if apotentialfailure.isFailure then println("No good")`
	- orElse
		- to run a backup method or code in case of failure of the base method or code
		- `Try(unsafeMethod).orElse(Try(backupMethod)) //Success('S all good man)`
	- map
		- `Success(3).map(_ * 2)` returns another `Sucess[Int]` 
		- applying map on a failure returns the same failure
	- flatMap
		- `Success(2).flatMap(x => Success(x * 10))`
		- `println(s"flat map failure ${aFailure1.flatMap(x => Success(2*1))}")`
			- returns a failure only
		- `Success(2).flatMap(x => Failure(new RuntimeException("It's not goog1")))`
			- worked pretty fine and returned a failure object
	- filter
		- only method that can return a failure from a success object is what he said
		- `println(Success(2).filter(_ > 10)) // Failure(java.util.NoSuchElementException: Predicate does not hold for 2)`
		- `aFailure1.filter(_ >10)` returns the same failure object
	- obviously we can use for comprehension as map, flatMap and filter are defined for Try
- if we are designing an API, if we know that code might throw an exception wrap the code in a Try instead
```
def betterUnsafeMethod: Try[String] = Failure(new RuntimeException("Hey"))  
def betterBackupMethod: Try[String] = Try("new Hey")  
println(betterUnsafeMethod orElse betterBackupMethod) // Success("new Hey")
```


```
val aFailure1: Try[Int] = Failure(new RuntimeException("It's not goog"))  
println(aFailure1.map(x => x * 2)) // returns the same object
```